/**
 * Minimal types mirrored from the main Toxen app, kept in sync manually.
 * Avoids pulling in React / Electron dependencies from the main project.
 */

export interface ISongPaths {
  dirname: string;
  media: string;
  background: string;
  subtitles: string;
  storyboard: string;
}

export interface ISong {
  uid: string;
  artist: string;
  coArtists: string[];
  title: string;
  album: string;
  genre: string;
  source: string;
  tags: string[];
  paths: ISongPaths;
  visualizerColor: string;
  visualizerStyle: string;
  visualizerIntensity: number;
  visualizerShuffle: boolean;
  visualizerNormalize: boolean;
  visualizerForceRainbowMode: boolean;
  visualizerPulseBackground: "pulse" | "pulse-off" | null;
  visualizerGlow: boolean;
  year: number;
  language: string;
  subtitleDelay: number;
  floatingTitle: boolean;
  floatingTitleText: string;
  starRushEffect: boolean | null;
  starRushIntensity: number | null;
  backgroundDim: number | null;
  autogeneratedTheme: boolean | null;
  hash: string;
  duration: number;
  files: Record<string, { time: number; action: "d" | "u" }>;
  playlistSettings?: Record<string, Partial<ISong>>;
}

export interface ISettings {
  libraryDirectory: string;
  isRemote: boolean;
  volume: number;
  repeat: boolean;
  shuffle: boolean;
  panelVerticalTransition: boolean;
  panelDirection: "left" | "right";
  exposePanelIcons: boolean;
  panelWidth: number;
  sidepanelBackground: string;
  restoreWindowSize: boolean;
  windowWidth: number;
  windowHeight: number;
  pauseWithClick: boolean;
  theme: string;
  visualizerColor: string;
  visualizerStyle: string;
  visualizerIntensity: number;
  visualizerNormalize: boolean;
  visualizerShuffle: boolean;
  visualizerRainbowMode: boolean;
  visualizerPulseBackground: boolean;
  visualizerGlow: boolean;
  backgroundDynamicLighting: boolean;
  fftSize: number;
  autogeneratedTheme: boolean;
  defaultBackground: string;
  defaultBackgrounds: string[];
  shuffleDefaultBackgrounds: boolean;
  backgroundDim: number;
  showAdvancedSettings: boolean;
  remoteServer: string;
  progressBarShowMs: boolean;
  discordPresence: boolean;
  discordPresenceDetailed: boolean;
  hueEnabled: boolean;
  hueBridgeIp: string;
  hueUsername: string;
  hueClientkey: string;
  hueEntertainmentAreaId: string;
  acceptedResponsibility: boolean;
  remoteSyncOnStartup: boolean;
  remoteSyncOnSongEdit: boolean;
  hideOffScreenSongElements: boolean;
  enableThumbnailCache: boolean;
  starRushEffect: boolean;
  starRushIntensity: number;
  audioEffectsEnabled: boolean;
  audioReverbLevel: number;
  audioEchoLevel: number;
  audioBassBoostLevel: number;
  audio3DLevel: number;
  crossfadeEnabled: boolean;
  crossfadeDuration: number;
  lastShownChangeNotesVersion: string;
  enabledExtensions: Record<string, boolean>;
}
